theme: jekyll-theme-cayman
title: Gene Discovery Through Computational Biology
description: Comparative and population genomics -- Simulation and design of genetic experiments -- Visualization of integrated crop data
